stages:
  - mpi
  - legion

variables:
  PROJECT_NAME: flecsolve
  ENABLE_CDASH: false
  # use this variable if there is a xcap/deployment MR you want to use instead
  PROJECT_SPACK_ENV_VERSION: mr/75/2024-10-15

include:
 - .gitlab/common.yml

darwin_mpi_serial_mpich_debug:
  stage: mpi
  extends: [.ascgit_job, .darwin_job, .darwin_regular_job, .build_and_test]
  needs: []
  variables:
    SPACK_ENV_NAME: mpi/serial/mpich-debug
    SUBMIT_TO_CDASH: "${ENABLE_CDASH}"

darwin_legion_serial_mpich_debug:
  stage: mpi
  extends: [.ascgit_job, .darwin_job, .darwin_regular_job, .build_and_test]
  needs: []
  variables:
    SPACK_ENV_NAME: legion/serial/mpich-debug
    SUBMIT_TO_CDASH: "${ENABLE_CDASH}"

