stages:
  - Canary
  - Environment
  - Build + Unit Tests
  - Final

include: .gitlab/environments.yml


format:diff:
  extends: .diff_format_template
  dependencies: []
  only:
    - merge_requests
  variables:
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi-linalg
    IMAGE: util-fedora-35
    FORMAT_VERSION: 13.0.0
    CXX_COMPILER: clang++
    CXX_FLAGS: -fcolor-diagnostics
    C_COMPILER: clang
    C_FLAGS: ${CXX_FLAGS}
  allow_failure: true

format:check:
  extends: .check_format_template
  needs:
    - job: format:diff
      artifacts: true
  only:
    - merge_requests
  variables:
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi-linalg
    IMAGE: util-fedora-35


#------------------------------------------------------------------------------#
# Build and unit tests for default settings.
#------------------------------------------------------------------------------#

mpich-defaults:
  extends: .defaults_build_template
  needs:
    ["mpich"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '2'
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: rockylinux

#------------------------------------------------------------------------------#
# Build and unit tests for Legion backend with MPICH provider,
# and GNU compiler toolchain.
#------------------------------------------------------------------------------#

mpich-legion-gnu:
  extends: .build_template
  needs:
    ["mpich-debug"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '2'
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: rockylinux
    BUILD_TYPE: Debug
    BACKEND: legion
    CXX_COMPILER: g++
    CXX_FLAGS: ''
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: ''

mpich-legion-gnu:release:
  extends: .build_template
  needs:
    ["mpich"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '2'
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: rockylinux
    BUILD_TYPE: Release
    BACKEND: legion
    CXX_COMPILER: g++
    CXX_FLAGS: ''
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: ''

#------------------------------------------------------------------------------#
# Build and unit tests for MPI backend with MPICH provider,
# and GNU compiler toolchain.
#------------------------------------------------------------------------------#

mpich-mpi-gnu:
  extends: .build_template
  needs:
    ["mpich-debug"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '2'
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: rockylinux
    BUILD_TYPE: Debug
    BACKEND: mpi
    CXX_COMPILER: g++
    CXX_FLAGS: ''
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: ''

mpich-mpi-gnu:release:
  extends: .build_template
  needs:
    ["mpich"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '2'
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: rockylinux
    BUILD_TYPE: Release
    BACKEND: mpi
    CXX_COMPILER: g++
    CXX_FLAGS: ''
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: ''

#------------------------------------------------------------------------------#
# Build and unit tests for Legion backend with OpenMPI provider,
# and GNU compiler toolchain.
#------------------------------------------------------------------------------#

openmpi-legion-gnu:
  extends: .build_template
  needs:
    ["openmpi-debug"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '2'
    MPI_PROVIDER: openmpi
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: rockylinux
    BUILD_TYPE: Debug
    BACKEND: legion
    CXX_COMPILER: g++
    CXX_FLAGS: ''
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: ''

openmpi-legion-gnu:release:
  extends: .build_template
  needs:
    ["openmpi"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '2'
    MPI_PROVIDER: openmpi
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: rockylinux
    BUILD_TYPE: Release
    BACKEND: legion
    CXX_COMPILER: g++
    CXX_FLAGS: ''
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: ''

#------------------------------------------------------------------------------#
# Build and unit tests for MPI backend with OpenMPI provider,
# and GNU compiler toolchain.
#------------------------------------------------------------------------------#

openmpi-mpi-gnu:
  extends: .build_template
  needs:
    ["openmpi-debug"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '2'
    MPI_PROVIDER: openmpi
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: rockylinux
    BUILD_TYPE: Debug
    BACKEND: mpi
    CXX_COMPILER: g++
    CXX_FLAGS: ''
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: ''

openmpi-mpi-gnu:release:
  extends: .build_template
  needs:
    ["openmpi"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '2'
    MPI_PROVIDER: openmpi
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: rockylinux
    BUILD_TYPE: Release
    BACKEND: mpi
    CXX_COMPILER: g++
    CXX_FLAGS: ''
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: ''

#------------------------------------------------------------------------------#
# Build and unit tests for Legion backend with MPICH provider,
# and Clang compiler toolchain.
#------------------------------------------------------------------------------#

mpich-legion-clang:
  extends: .build_template
  needs:
    ["mpich-clang-debug"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '2'
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: fedora-34
    BUILD_TYPE: Debug
    BACKEND: legion
    CXX_COMPILER: clang++
    CXX_FLAGS: -fcolor-diagnostics
    C_COMPILER: clang
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: ''

#------------------------------------------------------------------------------#
# Build and unit tests for MPI backend with MPICH provider,
# and Clang compiler toolchain.
#------------------------------------------------------------------------------#

mpich-mpi-clang:
  extends: .build_template
  needs:
    ["mpich-clang-debug"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '2'
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: fedora-34
    BUILD_TYPE: Debug
    BACKEND: mpi
    CXX_COMPILER: clang++
    CXX_FLAGS: -fcolor-diagnostics
    C_COMPILER: clang
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: ''

#------------------------------------------------------------------------------#
# Build and unit tests for MPI backend with OpenMPI provider,
# and Clang compiler toolchain.
#------------------------------------------------------------------------------#

openmpi-mpi-clang:
  extends: .build_template
  needs:
    ["openmpi-clang-debug"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '2'
    MPI_PROVIDER: openmpi
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: fedora-34
    BUILD_TYPE: Debug
    BACKEND: mpi
    CXX_COMPILER: clang++
    CXX_FLAGS: -fcolor-diagnostics
    C_COMPILER: clang
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: ''

